[package]
name = "merkle-accumulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.9.9"
rand_distr = "0.4.3"
rand = "0.7"
