[programs.localnet]
merkle_wallet = "7iNZXYZDn1127tRp1GSe3W3zGqGNdw16SiCwANNfTqXH"

[[test.genesis]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
program = "/Users/jarryxiao/solana-program-library/target/deploy/spl_associated_token_account.so"

[[test.genesis]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
program = "/Users/jarryxiao/solana-program-library/target/deploy/spl_token_2022.so"

[[test.genesis]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
program = "/Users/jarryxiao/solana-program-library/target/deploy/spl_token.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "/Users/jarryxiao/Projects/metaplex-program-library/target/deploy/mpl_token_metadata.so"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/jarryxiao/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
