[programs.localnet]
merkle_wallet = "ALNjRQ3aaLsTY9p8FyRUt8dpEWBF1DvTiD8QcLffBKHn"
gummyroll = "4L5JPAZyZ9eijKREpLAKGNNjCYVX5e1H53DvvweiMNnG"

[[test.genesis]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
program = "deps/solana-program-library/target/deploy/spl_associated_token_account.so"

[[test.genesis]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
program = "deps/solana-program-library/target/deploy/spl_token_2022.so"

[[test.genesis]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
program = "deps/solana-program-library/target/deploy/spl_token.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "deps/metaplex-program-library/token-metadata/target/deploy/mpl_token_metadata.so"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.ts"
