version: "3.9"
services:
  ingester:
    volumes:
      - ./target/debug/ingest:/bin/ingest
    environment:
      BIN: /bin/ingest
    depends_on:
      - api
      - redis
    restart: always
    image: merkle-wallet_api
  api:
    volumes:
      - ./target/debug/api:/bin/api
    restart: always
    build:
      context: .
      dockerfile: Api.Dockerfile
    ports:
      - "9090:9090"
  redis:
    cpu_count: 2
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: solana # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: solana # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: solana
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db-data/:/var/lib/postgresql/data/
  solana:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
    - ./ledger:/config:rw
    - ./docker-vol:/so:rw
    environment:
      RUST_LOG: warn
    ports:
      - "8900:8900"
      - "8001:8001"
      - "8899:8899"
      - "9900:9900"